[[constraint]]
  name = "github.com/gobuffalo/buffalo"
  version = "0.10.2"

[[constraint]]
  name = "github.com/gorilla/context"
  version = "1.1.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.0"

[[override]]
  name = "github.com/satori/go.uuid"
  revision = "36e9d2ebbde5e3f13ab2e25625fd453271d6522e"
[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"
